Layout
Fabsolute/werewolf-client pull request #1
Opened 2023-07-31 09:14 UTC by mstfygci

![Werewolf](https://github.com/Fabsolute/werewolf-client/assets/34628811/2c27471b-2760-4aea-bc59-7cf4b0a3fe15)

2023-08-03 15:25 UTC, Fabsolute requested changes

2023-08-03 15:25 UTC, Fabsolute commented on src/App.tsx
> +import 'bootstrap-icons/font/bootstrap-icons.min.css'
These styles should be moved in `App.css` or `Layout` itself.

2023-08-03 15:25 UTC, Fabsolute commented on src/App.tsx
> +      {/*<button style={{position: 'absolute', top: 300, left: 300}}>Oy</button>*/}
should be removed

2023-08-03 15:25 UTC, Fabsolute commented on src/components/Info.tsx
> +    <Button variant="light" className="mt-3 d-flex" style={{width: 'auto'}}>
we shouldnt use inline styles

2023-08-03 15:25 UTC, Fabsolute commented on src/components/Info.tsx
> +          <ProgressBar variant="info" now={levelStatus} label={`${levelStatus}%`}/>
we should use `percentage` instead of `levelStatus`

2023-08-03 15:25 UTC, Fabsolute commented on src/components/Menu.tsx
> +}[]
This type is not representing an array. So it shouldn't be an array.

2023-08-03 15:25 UTC, Fabsolute commented on src/components/Menu.tsx
> +          <div className={`row justify-content-center ${index != 0 && ' mt-2'}`}>
key required

2023-08-03 15:25 UTC, Fabsolute commented on src/layout/Header.tsx
> +      <Button variant="light" className="mt-3 d-flex" style={{width: 'auto'}}>
We have info component. So, we shouldn't use the same codes here.

2023-08-09 13:31 UTC, mstfygci commented on src/App.tsx
> +import 'bootstrap-icons/font/bootstrap-icons.min.css'
moved to App.css

2023-08-09 13:31 UTC, mstfygci commented on src/App.tsx
> +      {/*<button style={{position: 'absolute', top: 300, left: 300}}>Oy</button>*/}
Removed

2023-08-09 13:32 UTC, mstfygci commented on src/components/Info.tsx
> +    <Button variant="light" className="mt-3 d-flex" style={{width: 'auto'}}>
removed

2023-08-09 13:32 UTC, mstfygci commented on src/components/Info.tsx
> +          <ProgressBar variant="info" now={levelStatus} label={`${levelStatus}%`}/>
Changed

2023-08-09 13:34 UTC, mstfygci commented on src/components/Menu.tsx
> +}[]
Removed from type and added to the used place

2023-08-09 13:36 UTC, mstfygci commented on src/components/Menu.tsx
> +          <div className={`row justify-content-center ${index != 0 && ' mt-2'}`}>
Added `key` property to ButtonType

2023-08-09 13:36 UTC, Fabsolute commented on src/components/Menu.tsx
> +          <div className={`row justify-content-center ${index != 0 && ' mt-2'}`}>
Div still creating without key.

2023-08-09 13:37 UTC, mstfygci commented on src/layout/Header.tsx
> +      <Button variant="light" className="mt-3 d-flex" style={{width: 'auto'}}>
Replaced with `Info` component

2023-08-09 13:41 UTC, Fabsolute requested changes

2023-08-09 13:41 UTC, Fabsolute commented on src/App.tsx
> +    <div style={{position: 'relative'}}>
inline style

2023-08-09 13:41 UTC, Fabsolute commented on src/components/Info.tsx
> +  return (
I think we should add space between codes and return.

2023-08-09 13:41 UTC, Fabsolute commented on src/components/Menu.tsx
> +    }, {
```suggestion
    }, 
    {
```

2023-08-09 13:41 UTC, Fabsolute commented on src/components/Info.tsx
> +  )
```suggestion
  );
```

2023-08-09 13:41 UTC, Fabsolute commented on src/layout/index.tsx
> +    </>
```suggestion
    return (
    <>
        <Header/>
        <main>{children}</main>
        <Footer/>
    </>
    );
```

2023-08-09 13:41 UTC, Fabsolute commented on src/layout/Header.tsx
> +
remove empty line

2023-08-09 13:42 UTC, Fabsolute commented
You shouldn't have to reply to my comments if you are okay with it. Just press the resolve conversation button.

2023-08-09 20:03 UTC, Fabsolute requested changes

2023-08-09 20:03 UTC, Fabsolute commented on src/components/Menu.tsx
> +}
`;`

You should check all my comments for the all project. So, we shouldn't repeat ourselves.

2023-08-09 20:03 UTC, Fabsolute commented on src/components/Menu.tsx
> +          <div className={`row justify-content-center ${index != 0 && ' mt-2'}`} key={`menu_${index}`}>
Keys shouldn't created with indexes. It is against their nature.

2023-08-10 06:37 UTC, Fabsolute commented on src/components/Menu.tsx
> +  color: string
use a semicolon instead of a comma.

2023-08-10 06:38 UTC, merged